#!groovy

// Generated by IBM TransformationAdvisor
// Tue Apr 16 06:38:56 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'customerorderservicesapp'
    mvnCommands = '--version'
    test='false'
}